name: Check and build
run-name: Checking and building the project
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install modules
        run: npm ci
      - name: Eslint
        run: npm run eslint
      - name: Stylelint
        run: npm run stylelint
      - name: Prettier
        run: npm run prettier-check
      - name: Build project
        run: npm run build